package com.teknatio.hiber;
// Generated 26-May-2017 22:24:04 by Hibernate Tools 5.2.0.Beta1

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private short id;
	private String firstName;
	private String lastName;
	private String userName;
	private String password;
	private String email;
	private String mobile;

	public Users() {
	}

	public Users(short id) {
		this.id = id;
	}

	public Users(short id, String firstName, String lastName, String userName, String password, String email,
			String mobile) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.userName = userName;
		this.password = password;
		this.email = email;
		this.mobile = mobile;
	}

	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

}
